{% set name = "flatsurf" %}
{% set version = "3.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatsurf/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5d4074606b01877e667a6a3d35944fdfb46b7cfa93959cef82542c7c60ebf7f

build:
  number: 0
  # dependency libeantic is not available for Windows on conda-forge yet
  skip: true  # [win]

outputs:
  - name: libflatsurf
    script: build-libflatsurf.sh  # [not win]
    script: build-libflatsurf.bat  # [win]
    run_exports:
      - {{ pin_subpackage("libflatsurf") }}
    requirements:
      build:
        - libtool    # [unix]
        - automake   # [unix]
        - make       # [unix]
        - gnuconfig  # [unix]
        - autotools_clang_conda  # [win]
        - {{ compiler('cxx') }}
      host:
        # We only need the libboost-headers at compile time. However, since we
        # use bits of boost in our API, code built against libflatsurf must be
        # built with a compatible version of the headers. Therefore, we add a
        # liboost pin to our run exports so libboost-headers are going to be
        # in a compatible version.
        - libboost-devel
        - fmt
        - gmp   # [unix]
        - mpir  # [win]
        - libflint
        - libintervalxt
        - libexactreal
        - libeantic
        - gmpxxll
    test:
      commands:
        - test -f $PREFIX/include/flatsurf/flatsurf.hpp  # [unix]
        - test -f $PREFIX/lib/libflatsurf${SHLIB_EXT}      # [unix]
  - name: pyflatsurf
    script: build-pyflatsurf.sh  # [not win]
    script: bld-pyflatsurf.bat  # [win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libtool   # [unix]
        - automake  # [unix]
        - make      # [unix]
        - autotools_clang_conda  # [win]
        - gnuconfig  # [unix]
        - {{ compiler('cxx') }}
      host:
        # Note that the libboost-devel from libflatsurf forces these headers to be
        # compatible with ones used when building libflatsurf.
        - libboost-headers
        - python
        - cppyy
        # Work around https://github.com/conda-forge/cppyy-feedstock/issues/78 on the CI machines.
        - libcxx<17  # [osx]
        - cppyythonizations
        - setuptools
        - pytest
        - pyexactreal
        - pyintervalxt
        - {{ pin_subpackage("libflatsurf") }}
      run:
        # cppyy dynamically compiles C++ wrappers at runtime, therefore we need C++ headers of boost.
        # Note that the libboost-devel from libflatsurf forces these headers to be
        # compatible with ones used when building libflatsurf.
        - libboost-headers
        - python
        - cppyy
        # Work around https://github.com/conda-forge/cppyy-feedstock/issues/78 on the CI machines.
        - libcxx<17  # [osx]
        - cppyythonizations
        - gmpxxyy
        - pyexactreal
        - pyintervalxt
        # A subpackage does not see the run_exports of another subpackage:
        # https://github.com/conda/conda-build/issues/3478
        - {{ pin_subpackage("libflatsurf") }}
    test:
      imports:
        - pyflatsurf

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Algorithms on Flat Triangulations
  dev_url: https://github.com/flatsurf/flatsurf

extra:
  recipe-maintainers:
    - saraedum
